name: Kompilasi Kernel Mi A1

on:
  workflow_dispatch: # Tombol manual untuk menjalankan compiler

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Kloning Source Code Kernel
      uses: actions/checkout@v4

    - name: Siapkan Lingkungan Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential libncurses5-dev libssl-dev xz-utils wget curl git libxml2 flex bison

    - name: Unduh Toolchain GCC/Clang Lama (Khusus Mi A1)
      run: |
        mkdir toolchain
        cd toolchain
        # Mengunduh Google Clang/GCC yang cocok untuk kernel Snapdragon 625 (tissot)
        wget https://googlesource.com
        tar -xf master.tar.gz
        cd ..

    - name: Proses Kompilasi Kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=$(pwd)/toolchain/bin/aarch64-linux-android-
        make tissot_defconfig
        make -j$(nproc)

    - name: Unggah Hasil Kernel (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-MiA1-Tissot
        path: arch/arm64/boot/Image.gz-dtb
        
